Added wrapper for ClipperOffset algorithm to fix internal exception
SixLabors/ImageSharp.Drawing pull request #145
Opened 2021-06-19 23:06 UTC by obayomy

### Prerequisites

- [ ] I have written a descriptive pull-request title
- [ ] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp.Drawing/pulls) open
- [ ] I have verified that I am following matches the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [ ] I have provided test coverage for my change (where applicable)

### Description

- Made a wrapper for `ClipperOffset` in the same manner of `Clipper `wrapper in `PolygonsClipper` 
- Added check for the Nan case in #13

2021-06-19 23:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SixLabors/ImageSharp.Drawing?pullRequest=145) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SixLabors/ImageSharp.Drawing?pullRequest=145) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SixLabors/ImageSharp.Drawing?pullRequest=145) it.</sub>

2021-06-20 14:11 UTC, antonfirsov approved these changes
The issue described in #13 is that `ClipperException` is internal.

This is likely a mistake, since [`SixLabors.ImageSharp.Drawing.PolygonClipper.Clipper`](https://github.com/SixLabors/ImageSharp.Drawing/blob/c29e5de8bb1ed0afd11d71cb75ede5fd4bee0644/src/ImageSharp.Drawing/Shapes/PolygonClipper/Clipper.cs) is public. (Which I haven't noticed when opening that issue.)

The way to fix #13 is to make `ClipperException` public and document it in all methods that can possibly throw it. (All methods in `OutlinePathExtensions` or more).

The new `ClipperOffset` API needs justification, examples, an API review, and extensive test coverage before we can merge it.

2021-06-20 21:14 UTC, obayomy commented
Thank you for clarifying.

The current boundary between the `ImageSharp.Drawing.Shapes` and `ClipperLib` is a bit confusing to me as there are two different approaches for using `ClipperLib`: the `ClipPathExtensions` uses the external library through the `PolygonClipper.Clipper`  wrapper:
https://github.com/SixLabors/ImageSharp.Drawing/blob/423bf06a6b8bfce3a9991bede8af3e550c6742ca/src/ImageSharp.Drawing/Shapes/ClipPathExtensions.cs#L20-L30
While the `OutlinePathExtensions` uses the external library directly:
https://github.com/SixLabors/ImageSharp.Drawing/blob/423bf06a6b8bfce3a9991bede8af3e550c6742ca/src/ImageSharp.Drawing/Shapes/OutlinePathExtensions.cs#L80-L88
I moved the `ClipperLib` calls in `OutlinePathExtensions` to the new `PolygonClipper.Clipper` because I think it should be beneficial for the following points:

1. Make the usage of `ClipperLib` consistent.
2. Help when wrapping the internal `ClipperLib.ClipperException`  to a public one, as the lines that makes direct calls to `ClipperLib` will be minimized  and located only in the API. 
3. Help when working with #10 as new functions will be exposed directly from the API

2021-06-20 21:22 UTC, obayomy commented on src/ImageSharp.Drawing/Shapes/PolygonClipper/ClipperOffset.cs
> +    public class ClipperOffset
The current boundary between the `ImageSharp.Drawing.Shapes` and `ClipperLib` is a bit confusing to me as there are two different approaches for using `ClipperLib`: the `ClipPathExtensions` uses the external library through the `PolygonClipper.Clipper`  wrapper:
https://github.com/SixLabors/ImageSharp.Drawing/blob/423bf06a6b8bfce3a9991bede8af3e550c6742ca/src/ImageSharp.Drawing/Shapes/ClipPathExtensions.cs#L20-L30
While the `OutlinePathExtensions` uses the external library directly:
https://github.com/SixLabors/ImageSharp.Drawing/blob/423bf06a6b8bfce3a9991bede8af3e550c6742ca/src/ImageSharp.Drawing/Shapes/OutlinePathExtensions.cs#L80-L88
I moved the `ClipperLib` calls in `OutlinePathExtensions` to the new `PolygonClipper.Clipper` because I think it should be beneficial for the following points:

1. Make the usage of `ClipperLib` consistent.
2. Help when wrapping the internal `ClipperLib.ClipperException`  to a public one, as the lines that makes direct calls to `ClipperLib` will be minimized  and located only in the API. 
3. Help when working with #10 as new functions will be exposed directly from the API

2021-06-20 21:39 UTC, obayomy commented on src/ImageSharp.Drawing/Shapes/PolygonClipper/ClipperOffset.cs
> +    public class ClipperOffset
An example for the second point: 
When translating the exception that can be raised when calling `ClipperLib.ClipperOffset.AddPath()`  to a public one, only this line would be translated:
```
  lock (this.syncRoot)
  {
      this.innerClipperOffest.AddPath(points, this.Convert(jointStyle), endCapStyle);
  }
```
While trying to translate in `OutlinePathExtensions` will require translating every line/method that uses the external library

2021-06-20 21:50 UTC, obayomy commented on src/ImageSharp.Drawing/Shapes/PolygonClipper/ClipperOffset.cs
> +    public class ClipperOffset
I only made the `PolygonsClipper.ClipperOffset` public to be in the same manner as `PolygonsClipper.Clipper`. However, I think both should be internal, and the 'PolygonsClipper.ClipperException' should be changed to public as you clarified.

2021-06-20 22:35 UTC, obayomy commented on src/ImageSharp.Drawing/Shapes/PolygonClipper/ClipperOffset.cs
> +                if (float.IsNaN(v.X) || float.IsNaN(v.Y))
Okay, I will remove it and translate the internal exception instead.

2021-06-21 16:02 UTC, antonfirsov commented on src/ImageSharp.Drawing/Shapes/PolygonClipper/ClipperOffset.cs
> +    public class ClipperOffset
Hm, this leads very far. To solve #10 in general, I would prefer to see and discuss an API proposal before going into implementation details.

I also feel like it would be better to keep `Clipper` internal, since a general solution for #10 might break that API, but I'm not sure about this, could use some help from @tocsoft to decide. Unfortunately, I lack the time to think about a proper API for this alone. (And it's not a high-priority thing to get 1.0 released.)

If  @tocsoft doesn't get the chance to react here, let's just turn `ClipperOffest` for now.

2021-07-13 13:52 UTC, JimBobSquarePants requested changes
More changes than I would have initially done but I see why you have made them and they are definitely beneficial. If we can simplify the exception handling then I'm happy to merge this. Thanks!

2021-07-13 13:52 UTC, JimBobSquarePants commented on src/ImageSharp.Drawing/Shapes/PolygonClipper/ClipperOffset.cs
> +                catch (ClipperLib.ClipperException exception)
Took me a while to get my head around this but I think I understand the intent here. 

We cannot, however wrap the exception in this manner since the stack trace will be lost. 

There are two ways to deal with this. 

1. Continue to use the `try...catch` pattern but wrap `InvalidOperationException` instead of `ClipperLib.ClipperException`, passing the type as an internal exception.
2. Use only a single public `ClipperException` everywhere and don't use `try... catch`.

I would go with option 2 since the first option seems like massive complexity where there doesn't need to be.

2021-07-13 13:52 UTC, JimBobSquarePants commented on src/ImageSharp.Drawing/Shapes/PolygonClipper/ClipperOffset.cs
> +                throw new ArgumentNullException(nameof(path));
Use `Guard.NotNull(...)`

2021-07-13 13:52 UTC, JimBobSquarePants commented on src/ImageSharp.Drawing/Shapes/OutlinePathExtensions.cs
> +        /// <exception cref="ClipperException">Execute: Couldn't caculate Offset</exception>
`calculate`, here and elsewhere

2021-07-14 07:14 UTC, obayomy commented on src/ImageSharp.Drawing/Shapes/PolygonClipper/ClipperOffset.cs
> +                throw new ArgumentNullException(nameof(path));
Replaced all null checking with `Guard` in `ClipperOffset.cs `as well as `Clipper.cs`

2021-07-14 07:16 UTC, obayomy commented on src/ImageSharp.Drawing/Shapes/OutlinePathExtensions.cs
> +        /// <exception cref="ClipperException">Execute: Couldn't caculate Offset</exception>
Replaced `Execute` with `Calculate` in all places

2021-07-14 07:26 UTC, tocsoft commented on src/ImageSharp.Drawing/Shapes/OutlinePathExtensions.cs
> +        /// <exception cref="ClipperException">Execute: Couldn't caculate Offset</exception>
The issue wont have been the word Execute but the miss-spelling of `calculate`

```diff
-      /// <exception cref="ClipperException">Execute: Couldn't caculate Offset</exception>
+      /// <exception cref="ClipperException">Execute: Couldn't calculate Offset</exception>
```

2021-07-14 07:29 UTC, obayomy commented on src/ImageSharp.Drawing/Shapes/PolygonClipper/ClipperOffset.cs
> +                catch (ClipperLib.ClipperException exception)
Applied the second option. Changed the access modifier of  `ClipperLib.ClipperException` in `clipper.cs` to `public`, and excluded the `ClipperException.cs` in `PolygonClipper` Folder to avoid conflict.

2021-07-14 08:47 UTC, JimBobSquarePants commented on tests/ImageSharp.Drawing.Tests/Shapes/PolygonClipper/ClipperTests.cs
> +                Assert.True(ex is ClipperLib.ClipperException);
We don't want the exception to be a nested type.

2021-07-14 08:49 UTC, JimBobSquarePants commented on src/ImageSharp.Drawing/Shapes/OutlinePathExtensions.cs
> +        /// <exception cref="ClipperException">Calculate: Couldn't caculate Offset</exception>
Sorry, I meant fix the spelling. `caculate` should be `calculate`

2021-07-14 09:31 UTC, JimBobSquarePants commented on src/ImageSharp.Drawing/Shapes/PolygonClipper/ClipperOffset.cs
> +                catch (ClipperLib.ClipperException exception)
If the second type is unused don’t be afraid to delete it.

2021-07-14 10:15 UTC, obayomy commented on tests/ImageSharp.Drawing.Tests/Shapes/PolygonClipper/ClipperTests.cs
> +                Assert.True(ex is ClipperLib.ClipperException);
`ClipperLib` is not a type, it's just the namespace of the clipper library.

2021-07-14 10:48 UTC, obayomy commented on src/ImageSharp.Drawing/Shapes/OutlinePathExtensions.cs
> +        /// <exception cref="ClipperException">Calculate: Couldn't caculate Offset</exception>
No problem. Sorry for missing the type, will fix it.

2021-07-14 11:06 UTC, JimBobSquarePants commented on tests/ImageSharp.Drawing.Tests/Shapes/PolygonClipper/ClipperTests.cs
> +                Assert.True(ex is ClipperLib.ClipperException);
Ah right… can you please remove that namespace prefix then. Once you’ve removed the duplicate type there shouldn’t be any collisions. Thanks!

2021-07-14 15:06 UTC, JimBobSquarePants commented on src/ImageSharp.Drawing/Shapes/PolygonClipper/ClipperOffset.cs
> +    public class ClipperOffset
>I also feel like it would be better to keep Clipper internal
@antonfirsov I'm seconding that and making it internal for now.

2021-07-14 15:09 UTC, JimBobSquarePants commented
@obayomy I had some time so pushed the final tweaks to give you a hand. Thanks ever so much for your help! 👍

2021-07-14 15:14 UTC, JimBobSquarePants approved these changes

2021-07-14 15:15 UTC, merged