fixes #175 - Text gets chopped when rotated >60 degrees.
SixLabors/ImageSharp.Drawing pull request #191
Opened 2022-01-07 23:33 UTC by replaysMike

The glyph size is not rendered with enough space when rotated, this fixes the issue at all rotation angles

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp.Drawing/pulls) open
- [x] I have verified that I am following matches the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description
The font glyph isn't rendered with enough space to allow for text rotations. I modified the code that adjusts for that as part of the offset. Tested with a large range of fonts at varying rotations, and added appropriate tests for comparing expected output.

These tests will likely need to be modified when a fix is present for why rotated text gets offset shifted horizontally.

2022-01-07 23:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SixLabors/ImageSharp.Drawing?pullRequest=191) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SixLabors/ImageSharp.Drawing?pullRequest=191) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SixLabors/ImageSharp.Drawing?pullRequest=191) it.</sub>

2022-01-08 08:39 UTC, JimBobSquarePants commented
I tried to push some fixes to your tests but Git LFS and GitHub don't work well together and won't let me do so. I'll comment with the required changes instead.

2022-01-08 08:46 UTC, JimBobSquarePants requested changes
Can't really comment on the fix but have spotted some issues with the tests which are causing the offset your seeing. I've commented with the fixes.

2022-01-08 08:46 UTC, JimBobSquarePants commented on tests/ImageSharp.Drawing.Tests/Issues/Issue_175.cs
> +    public class Issue_175
You're better off adding the following tests to `DrawTextOnImageTests`

```c#
[Theory]
[WithSolidFilledImages(300, 200, nameof(Color.White), PixelTypes.Rgba32, TestFonts.OpenSans, 32, 75F)]
[WithSolidFilledImages(300, 200, nameof(Color.White), PixelTypes.Rgba32, TestFonts.OpenSans, 40, 90F)]
public void CanRotateFilledFont_Issue175<TPixel>(
    TestImageProvider<TPixel> provider,
    string fontName,
    int fontSize,
    float angle)
    where TPixel : unmanaged, IPixel<TPixel>
{
    Font font = CreateFont(fontName, fontSize);
    const string text = "QuickTYZ";
    AffineTransformBuilder builder = new AffineTransformBuilder().AppendRotationDegrees(angle);

    TextOptions textOptions = new(font);
    FontRectangle bounds = TextMeasurer.Measure(text, textOptions);
    provider.RunValidatingProcessorTest(
        x => x.SetDrawingTransform(builder.BuildMatrix(Rectangle.Round(new RectangleF(bounds.X, bounds.Y, bounds.Width, bounds.Height))))
        .DrawText(textOptions, text, Color.Black),
        $"F({fontName})-S({fontSize})-A({angle})-{ToTestOutputDisplayText(text)})",
        TextDrawingComparer,
        appendPixelTypeToFileName: false,
        appendSourceFileOrDescription: true);
}

[Theory]
[WithSolidFilledImages(300, 200, nameof(Color.White), PixelTypes.Rgba32, TestFonts.OpenSans, 32, 75F, 1)]
[WithSolidFilledImages(300, 200, nameof(Color.White), PixelTypes.Rgba32, TestFonts.OpenSans, 40, 90F, 2)]
public void CanRotateOutlineFont_Issue175<TPixel>(
    TestImageProvider<TPixel> provider,
    string fontName,
    int fontSize,
    float angle,
    int strokeWidth)
    where TPixel : unmanaged, IPixel<TPixel>
{
    Font font = CreateFont(fontName, fontSize);
    const string text = "QuickTYZ";
    AffineTransformBuilder builder = new AffineTransformBuilder().AppendRotationDegrees(angle);

    TextOptions textOptions = new(font);
    FontRectangle bounds = TextMeasurer.Measure(text, textOptions);
    provider.RunValidatingProcessorTest(
        x => x.SetDrawingTransform(builder.BuildMatrix(Rectangle.Round(new RectangleF(bounds.X, bounds.Y, bounds.Width, bounds.Height))))
        .DrawText(textOptions, text, Pens.Solid(Color.Black, strokeWidth)),
        $"F({fontName})-S({fontSize})-A({angle})-STR({strokeWidth})-{ToTestOutputDisplayText(text)})",
        TextDrawingComparer,
        appendPixelTypeToFileName: false,
        appendSourceFileOrDescription: true);
}
```

2022-01-08 08:46 UTC, JimBobSquarePants commented on tests/ImageSharp.Drawing.Tests/TestImages.cs
> +            public const string Issue175Filled = "Png/issues/issue175_filled.png";
Can you please delete these and the images themselves. Issue images are for decoder tests. We haven't cleaned up these since moving Drawing into a separate repository.

2022-01-08 08:46 UTC, JimBobSquarePants commented on tests/ImageSharp.Drawing.Tests/Issues/Issue_175.cs
> +    public class Issue_175
Add the following images to `\tests\Images\ReferenceOutput\Drawing\Text\DrawTextOnImageTests` for the tests to reference against.

[references.zip](https://github.com/SixLabors/ImageSharp.Drawing/files/7832905/references.zip)

2022-01-08 08:46 UTC, JimBobSquarePants commented on src/ImageSharp.Drawing/Processing/Processors/Text/DrawTextProcessor{TPixel}.cs
> +                this.offset = (int)textOptions.Font.Size;
Does this become an arms race or is the value calculated from theory? @antonfirsov @tocsoft I'm not an expert in this area so could do with your input please.

2022-01-08 22:13 UTC, replaysMike commented on src/ImageSharp.Drawing/Processing/Processors/Text/DrawTextProcessor{TPixel}.cs
> +                this.offset = (int)textOptions.Font.Size;
I'm not an expert on this either as it's fairly complicated, but this worked well on a wide variety of tests. I figured the original author wasn't going to provide input as this ticket has been open for a year

2022-01-08 22:14 UTC, replaysMike commented on tests/ImageSharp.Drawing.Tests/TestImages.cs
> +            public const string Issue175Filled = "Png/issues/issue175_filled.png";
yep. The only problem with this is then there is nothing to Assert in the tests, but if you guys are fine with that (many other tests I reviewed don't have assertions)

2022-01-08 23:14 UTC, JimBobSquarePants commented on tests/ImageSharp.Drawing.Tests/TestImages.cs
> +            public const string Issue175Filled = "Png/issues/issue175_filled.png";
The assertion actually takes place in `RunValidatingProcessorTest`. That’s why I provided the rewrite.

2022-01-08 23:16 UTC, replaysMike commented on tests/ImageSharp.Drawing.Tests/TestImages.cs
> +            public const string Issue175Filled = "Png/issues/issue175_filled.png";
> The assertion actually takes place in `RunValidatingProcessorTest`. That’s why I provided the rewrite.

yup I see that now, I'm just trying to work out how to save those images that are required for comparison, I tried doing it manually but they fail during comparison

2022-01-08 23:18 UTC, replaysMike commented on tests/ImageSharp.Drawing.Tests/TestImages.cs
> +            public const string Issue175Filled = "Png/issues/issue175_filled.png";
looks like I have it working now, will push in a few min

2022-01-08 23:28 UTC, replaysMike commented on src/ImageSharp.Drawing/Processing/Processors/Text/DrawTextProcessor{TPixel}.cs
> +                this.offset = (int)textOptions.Font.Size;
will resolve this for now to see how the CI system behaves with this. If @antonfirsov or @tocsoft has any input regarding the change would be appreciated

2022-01-09 13:26 UTC, JimBobSquarePants commented
@replaysMike Can you please do me a favor and update the following reference image? There's an invisible to the eye (0.0001%) diff being reported on our Windows CI build for this image and I can't get GitHub to let me make the change in your fork.
[FontShapesAreRenderedCorrectly_Solid400x45_(255,255,255,255)_OpenSans-Regular.ttf-20-Sphi-(0,0).zip](https://github.com/SixLabors/ImageSharp.Drawing/files/7835112/FontShapesAreRenderedCorrectly_Solid400x45_.255.255.255.255._OpenSans-Regular.ttf-20-Sphi-.0.0.zip)

Once that's updated and we have running tests I'll get this merged. Thanks!

2022-01-13 01:06 UTC, replaysMike commented
> @replaysMike Can you please do me a favor and update the following reference image? There's an invisible to the eye (0.0001%) diff being reported on our Windows CI build for this image and I can't get GitHub to let me make the change in your fork. [FontShapesAreRenderedCorrectly_Solid400x45_(255,255,255,255)_OpenSans-Regular.ttf-20-Sphi-(0,0).zip](https://github.com/SixLabors/ImageSharp.Drawing/files/7835112/FontShapesAreRenderedCorrectly_Solid400x45_.255.255.255.255._OpenSans-Regular.ttf-20-Sphi-.0.0.zip)
> 
> Once that's updated and we have running tests I'll get this merged. Thanks!

will do thanks! I was just re-looking into this issue glad you already found the problem.

2022-01-13 13:20 UTC, JimBobSquarePants commented
Let's get this merged! Thanks again!

2022-01-13 13:20 UTC, JimBobSquarePants approved these changes

2022-01-13 13:21 UTC, merged